import { Image } from 'expo-image';
import { router } from 'expo-router';
import { ArrowLeft, Check, ChevronRight, Trophy } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { IconButton, Screen, SectionTitle, commonStyles } from '@/components/kouponly-ui';
import { challenges, rewards } from '@/data/fixtures';
import { useAppStore } from '@/store/use-app-store';
import { colors, radius, shadow } from '@/theme';

export default function RewardsScreen(){const points=useAppStore(s=>s.points);return <Screen><View style={styles.nav}><IconButton label="Back" onPress={()=>router.back()}><ArrowLeft size={20} color={colors.ink}/></IconButton><Text style={styles.navTitle}>Challenges & rewards</Text><View style={{width:42}}/></View><View style={styles.hero}><View><Text style={styles.kicker}>YOUR POINTS</Text><Text style={styles.points}>{points}</Text><Text style={styles.heroBody}>Earned from useful actions, never chance.</Text></View><Trophy size={82} color={colors.lime} strokeWidth={1.4}/></View><View style={styles.section}><SectionTitle eyebrow="KEEP GOING" title="Active challenges"/></View><View style={styles.challenges}>{challenges.map((challenge)=><View key={challenge.id} style={styles.challenge}><View style={styles.check}><Check size={17} color={colors.ink}/></View><View style={{flex:1}}><Text style={styles.challengeTitle}>{challenge.title}</Text><Text style={styles.challengeBody}>{challenge.detail}</Text><View style={styles.progress}><View style={[styles.progressFill,{width:`${Math.min(100,challenge.progress/challenge.target*100)}%`}]} /></View><Text style={styles.progressText}>{challenge.progress}/{challenge.target} · +{challenge.points} points</Text></View></View>)}</View><View style={styles.section}><SectionTitle eyebrow="FIXED REWARDS" title="Spend your points"/></View><View style={styles.rewards}>{rewards.map((reward)=><Pressable key={reward.id} onPress={()=>router.push(`/reward/${reward.id}`)} style={styles.reward}><Image source={{uri:reward.image}} style={styles.rewardImage} contentFit="cover"/><View style={{flex:1}}><Text style={styles.rewardName}>{reward.name}</Text><Text style={commonStyles.muted}>{reward.detail}</Text></View><View style={styles.cost}><Text style={styles.costText}>{reward.points}</Text><ChevronRight size={14} color={colors.lime}/></View></Pressable>)}</View></Screen>}
const styles=StyleSheet.create({nav:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14},navTitle:{fontFamily:'Sora_700Bold',fontSize:13},hero:{minHeight:180,padding:22,borderRadius:radius.hero,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:colors.ink,...shadow.lime},kicker:{color:colors.lime,fontSize:9,fontWeight:'900',letterSpacing:1.4},points:{marginTop:5,color:colors.white,fontFamily:'Sora_800ExtraBold',fontSize:44},heroBody:{maxWidth:200,color:'#AAA',fontSize:10,lineHeight:15},section:{marginTop:29},challenges:{gap:10},challenge:{minHeight:112,padding:15,borderRadius:radius.xl,flexDirection:'row',gap:11,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line},check:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:colors.lime},challengeTitle:{fontFamily:'Sora_700Bold',fontSize:13},challengeBody:{marginTop:4,color:colors.muted,fontSize:9},progress:{height:6,marginTop:11,borderRadius:3,overflow:'hidden',backgroundColor:colors.cream},progressFill:{height:'100%',backgroundColor:colors.lime},progressText:{marginTop:5,color:colors.muted,fontSize:8,fontWeight:'800'},rewards:{gap:9},reward:{minHeight:90,padding:9,borderRadius:radius.lg,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line},rewardImage:{width:72,height:72,borderRadius:14},rewardName:{fontFamily:'Sora_700Bold',fontSize:12,marginBottom:5},cost:{minWidth:55,height:35,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:2,backgroundColor:colors.ink},costText:{color:colors.white,fontSize:9,fontWeight:'900'}});

