import { router } from 'expo-router';
import { BadgePercent, BriefcaseBusiness, ChevronRight, Gift, Settings, TicketPercent, Trophy, UserRound, WalletCards } from 'lucide-react-native';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { Screen } from '@/components/kouponly-ui';
import { useAppStore } from '@/store/use-app-store';
import { colors, radius, shadow } from '@/theme';

const menu = [
  { icon: UserRound, label: 'Personal details', path: '/account/personal' },
  { icon: BadgePercent, label: 'Savings activity', path: '/account/savings' },
  { icon: WalletCards, label: 'Creator earnings', path: '/account/earnings' },
  { icon: Trophy, label: 'Challenges & rewards', path: '/rewards' },
  { icon: TicketPercent, label: 'Membership', path: '/account/membership' },
  { icon: Gift, label: 'Gifts', path: '/account/gifts' },
  { icon: Settings, label: 'Preferences', path: '/account/settings' },
] as const;

export default function MeScreen() {
  const profile = useAppStore((state) => state.profile); const points=useAppStore((state)=>state.points); const applied=useAppStore((state)=>state.appliedCampaignIds.length);
  return <Screen style={{paddingHorizontal:0,paddingTop:0}}><View style={styles.hero}><View style={styles.heroTop}><Text style={styles.kicker}>YOUR SPACE</Text><Pressable accessibilityLabel="Settings" onPress={()=>router.push('/account/settings')} style={styles.settings}><Settings size={19} color={colors.white}/></Pressable></View><View style={styles.avatar}><Text style={styles.avatarText}>{profile.name.split(' ').map((part)=>part[0]).slice(0,2).join('')}</Text><View style={styles.status}/></View><Text style={styles.name}>{profile.name}</Text><Text style={styles.email}>{profile.email}</Text><View style={styles.stats}><View><Text style={styles.statValue}>₹2,400</Text><Text style={styles.statLabel}>saved this month</Text></View><View style={styles.divider}/><View><Text style={styles.statValue}>8</Text><Text style={styles.statLabel}>offers enjoyed</Text></View></View></View>
    <View style={styles.content}><Pressable onPress={()=>router.push('/account/savings')} style={styles.streak}><Text style={styles.streakNumber}>6</Text><View style={{flex:1}}><Text style={styles.small}>MONTHLY STREAK</Text><Text style={styles.cardTitle}>You’re on a roll</Text><Text style={styles.cardBody}>One more saving to beat July.</Text></View><ChevronRight size={18} color={colors.muted}/></Pressable>
      <Pressable onPress={()=>router.push('/grow?track=creator')} style={styles.creator}><View style={styles.creatorIcon}><BriefcaseBusiness size={22} color={colors.lime}/></View><View style={{flex:1}}><Text style={[styles.small,{color:colors.lime}]}>KOUPONLY CREATOR · ACCEPTED</Text><Text style={[styles.cardTitle,{color:colors.white}]}>₹12,500 earned · 3 campaigns ready</Text><Text style={[styles.cardBody,{color:'#AAA'}]}>{applied?`${applied} application${applied===1?'':'s'} in progress`:'Pick the briefs that fit your style.'}</Text></View><ChevronRight size={18} color={colors.white}/></Pressable>
      <Pressable onPress={()=>router.push('/rewards')} style={styles.creator}><View style={[styles.creatorIcon,{backgroundColor:colors.lime}]}><Trophy size={22} color={colors.ink}/></View><View style={{flex:1}}><Text style={[styles.small,{color:colors.lime}]}>CHALLENGES & REWARDS</Text><Text style={[styles.cardTitle,{color:colors.white}]}>{points} points · 3 challenges active</Text><Text style={[styles.cardBody,{color:'#AAA'}]}>Complete goals and redeem food or experiences.</Text></View><ChevronRight size={18} color={colors.white}/></Pressable>
      <View style={styles.menu}>{menu.map(({icon:Icon,label,path})=><Pressable key={label} onPress={()=>router.push(path)} style={({pressed})=>[styles.menuItem,pressed&&{opacity:.6}]}><View style={styles.menuIcon}><Icon size={19} color={colors.ink}/></View><Text style={styles.menuLabel}>{label}</Text><ChevronRight size={18} color={colors.muted}/></Pressable>)}</View>
      <Pressable onPress={()=>router.push('/account/help')} style={styles.help}><Text style={styles.helpText}>Help, feedback & legal</Text><ChevronRight size={17} color={colors.ink}/></Pressable><Text style={styles.version}>Kouponly native prototype · v1.0</Text>
    </View>
  </Screen>;
}

const styles=StyleSheet.create({hero:{padding:22,paddingTop:18,alignItems:'center',backgroundColor:colors.ink,borderBottomLeftRadius:34,borderBottomRightRadius:34},heroTop:{width:'100%',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{color:colors.lime,fontSize:9,fontWeight:'900',letterSpacing:1.4},settings:{width:38,height:38,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'#242424'},avatar:{width:76,height:76,marginTop:3,borderRadius:25,alignItems:'center',justifyContent:'center',backgroundColor:colors.lime},avatarText:{color:colors.ink,fontFamily:'Sora_800ExtraBold',fontSize:23},status:{position:'absolute',right:-2,bottom:-2,width:17,height:17,borderRadius:9,backgroundColor:colors.success,borderWidth:3,borderColor:colors.ink},name:{marginTop:13,color:colors.white,fontFamily:'Sora_800ExtraBold',fontSize:22},email:{marginTop:4,color:'#AAA',fontSize:10},stats:{width:'100%',marginTop:19,paddingTop:16,borderTopWidth:1,borderColor:'#303030',flexDirection:'row',justifyContent:'center',gap:28},statValue:{textAlign:'center',color:colors.white,fontFamily:'Sora_800ExtraBold',fontSize:17},statLabel:{marginTop:4,color:'#AAA',fontSize:8},divider:{width:1,height:36,backgroundColor:'#333'},content:{padding:20},streak:{minHeight:94,padding:14,flexDirection:'row',alignItems:'center',gap:11,borderRadius:radius.xl,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line},streakNumber:{width:47,height:47,paddingTop:12,borderRadius:16,overflow:'hidden',textAlign:'center',backgroundColor:colors.lime,fontFamily:'Sora_800ExtraBold',fontSize:17},small:{color:colors.muted,fontSize:8,fontWeight:'900',letterSpacing:1},cardTitle:{marginTop:4,color:colors.ink,fontFamily:'Sora_700Bold',fontSize:12},cardBody:{marginTop:4,color:colors.muted,fontSize:9},creator:{minHeight:104,marginTop:11,padding:14,flexDirection:'row',alignItems:'center',gap:11,borderRadius:radius.xl,backgroundColor:colors.ink,...shadow.card},creatorIcon:{width:47,height:47,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#252525'},menu:{marginTop:18,borderRadius:radius.xl,overflow:'hidden',backgroundColor:colors.white,borderWidth:1,borderColor:colors.line},menuItem:{minHeight:58,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:11,borderBottomWidth:1,borderColor:colors.line},menuIcon:{width:34,height:34,borderRadius:11,alignItems:'center',justifyContent:'center',backgroundColor:colors.cream},menuLabel:{flex:1,fontSize:11,fontWeight:'800'},help:{height:48,marginTop:13,paddingHorizontal:15,borderRadius:radius.md,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:colors.lime},helpText:{fontSize:10,fontWeight:'900'},version:{marginTop:22,textAlign:'center',color:colors.muted,fontSize:9}});
