import { router, useLocalSearchParams } from 'expo-router';
import { Check, Trophy, X } from 'lucide-react-native';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { rewards } from '@/data/fixtures'; import { useAppStore } from '@/store/use-app-store'; import { colors, radius, shadow } from '@/theme';
export default function RewardModal(){const {id}=useLocalSearchParams<{id:string}>();const reward=rewards.find(r=>r.id===id);const points=useAppStore(s=>s.points);const spend=useAppStore(s=>s.spendPoints);const [step,setStep]=useState<'confirm'|'pin'|'success'>('confirm');const [pin,setPin]=useState('');if(!reward)return null;const redeem=()=>{if(pin.length===4&&spend(reward.points))setStep('success')};return <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={styles.overlay}><View style={styles.sheet}><Pressable onPress={()=>router.back()} style={styles.close}><X size={19} color={colors.ink}/></Pressable><View style={styles.symbol}>{step==='success'?<Check size={26} color={colors.ink}/>:<Trophy size={26} color={colors.ink}/>}</View>{step==='confirm'?<><Text style={styles.kicker}>REWARD REDEMPTION</Text><Text style={styles.title}>Redeem {reward.name}?</Text><Text style={styles.body}>This costs {reward.points} points. You currently have {points} points.</Text><Button label={points>=reward.points?'Continue to partner PIN':'Not enough points'} disabled={points<reward.points} onPress={()=>setStep('pin')}/></>:null}{step==='pin'?<><Text style={styles.kicker}>PARTNER VERIFICATION</Text><Text style={styles.title}>Hand this phone to staff</Text><Text style={styles.body}>The partner enters their private four-digit PIN. Points deduct only after verification.</Text><TextInput autoFocus keyboardType="number-pad" secureTextEntry maxLength={4} value={pin} onChangeText={v=>setPin(v.replace(/\D/g,'').slice(0,4))} placeholder="••••" style={styles.pin}/><Button label="Verify and redeem" disabled={pin.length!==4} onPress={redeem}/></>:null}{step==='success'?<><Text style={styles.kicker}>REWARD READY</Text><Text style={styles.title}>Enjoy your {reward.name.toLowerCase()}</Text><Text style={styles.body}>The reward is now recorded in your activity. Show this confirmation to the partner.</Text><View style={styles.code}><Text>KOUPONLY REWARD</Text><Text style={styles.codeValue}>KPL-{reward.id.toUpperCase()}-{reward.points}</Text></View><Button label="Done" onPress={()=>router.back()}/></>:null}</View></KeyboardAvoidingView>}
function Button({label,onPress,disabled}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.button,disabled&&{opacity:.35,shadowOpacity:0}]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({overlay:{flex:1,justifyContent:'center',padding:20,backgroundColor:'rgba(0,0,0,.55)'},sheet:{padding:24,borderRadius:30,backgroundColor:colors.white},close:{position:'absolute',right:17,top:17,width:37,height:37,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:colors.cream},symbol:{width:54,height:54,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:colors.lime,marginBottom:18},kicker:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.3},title:{marginTop:7,color:colors.ink,fontFamily:'Sora_800ExtraBold',fontSize:23,lineHeight:28},body:{marginVertical:13,color:colors.muted,fontSize:12,lineHeight:19},pin:{height:64,marginVertical:10,borderRadius:radius.lg,borderWidth:1,borderColor:colors.ink,textAlign:'center',fontSize:26,letterSpacing:12,backgroundColor:colors.paper},button:{height:49,marginTop:8,borderRadius:radius.md,alignItems:'center',justifyContent:'center',backgroundColor:colors.ink,...shadow.lime},buttonText:{color:colors.white,fontSize:11,fontWeight:'900'},code:{marginVertical:14,minHeight:82,borderRadius:radius.lg,alignItems:'center',justifyContent:'center',backgroundColor:colors.lime},codeValue:{marginTop:5,fontFamily:'Sora_800ExtraBold',fontSize:17}});

